version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: finance_redis
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  mysql_data: